BEGIN TRANSACTION;

CREATE TABLE `User` (
	`Id`		INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Username`	TEXT NOT NULL UNIQUE,
	`Email`	TEXT NOT NULL UNIQUE,
	`Password`	TEXT NOT NULL,
	`Token` TEXT NOT NULL,
	FOREIGN KEY(`Username`) REFERENCES Marker
);

CREATE TABLE `PokemonType` (
	`Id`		INTEGER PRIMARY KEY AUTOINCREMENT,
	`Name`		TEXT UNIQUE
);

CREATE TABLE `Pokemon` (
	`Id`		INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`		TEXT NOT NULL UNIQUE,
	`ImagePath`	TEXT NOT NULL,
	`TypeFirst`	INTEGER NOT NULL,
	`TypeSecond`	INTEGER,
	FOREIGN KEY(`TypeFirst`) REFERENCES `PokemonType`,
	FOREIGN KEY(`TypeSecond`) REFERENCES `PokemonType`
);

CREATE TABLE `Marker` (
	`Id`		INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`UserId`	INTEGER NOT NULL,
	`PokemonId`	INTEGER NOT NULL,
	`Latitude`	DOUBLE  NOT NULL,
	`Longitude`	DOUBLE  NOT NULL,
	`TimeStamp`	TEXT NOT NULL,
	`LifePoints`	INTEGER NOT NULL,
	`Attack`	INTEGER NOT NULL,
	`Defense`	INTEGER NOT NULL,
	FOREIGN KEY (`UserId`) REFERENCES `User`,
	FOREIGN KEY(`PokemonId`) REFERENCES `Pokemon`
);

CREATE TABLE `MarkerVote` (
	`Id`		INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`UserId`	INTEGER NOT NULL,
	`MarkerId`	INTEGER NOT NULL,
	`IsUp`		BOOLEAN NOT NULL,
	FOREIGN KEY (`UserId`) REFERENCES `User`,
	FOREIGN KEY (`MarkerId`) REFERENCES `Marker`
);

INSERT INTO `PokemonType` (`Name`) VALUES
	("NORMAL"),
	("FIRE"),
	("WATER"),
	("ELECTRIC"),
	("GRASS"),
	("ICE"),
	("FIGHTING"),
	("POISON"),
	("GROUND"),
	("FLYING"),
	("PSYCHIC"),
	("BUG"),
	("ROCK"),
	("GHOST"),
	("DRAGON"),
	("DARK"),
	("STEEL"),
	("FAIRY");

INSERT INTO `Pokemon` (`Name`,`ImagePath`, `TypeFirst`, `TypeSecond`) VALUES
	("Abomasnow", "abomasnow.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="ICE")),
	("Abra", "abra.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Absol", "absol.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DARK"), NULL),
	("Accelgor", "accelgor.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), NULL),
	("Aegislash", "aegislash.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Aerodactyl", "aerodactyl.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Aggron", "aggron.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Aipom", "aipom.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Alakazam", "alakazam.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Alomomola", "alomomola.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Altaria", "altaria.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Amaura", "amaura.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Ambipom", "ambipom.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Amoonguss", "amoonguss.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Ampharos", "ampharos.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Anorith", "anorith.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Araquanid", "araquanid.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Arbok", "arbok.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), NULL),
	("Arcanine", "arcanine.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Arceus", "arceus.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Archen", "archen.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Archeops", "archeops.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Ariados", "ariados.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Armaldo", "armaldo.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Aromatisse", "aromatisse.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY"), NULL),
	("Aron", "aron.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Articuno", "articuno.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Audino", "audino.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Aurorus", "aurorus.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Avalugg", "avalugg.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), NULL),
	("Axew", "axew.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON"), NULL),
	("Azelf", "azelf.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Azumarill", "azumarill.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Azurill", "azurill.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Bagon", "bagon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON"), NULL),
	("Baltoy", "baltoy.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Banette", "banette.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST"), NULL),
	("Barbaracle", "barbaracle.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Barboach", "barboach.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND")),
	("Basculin", "basculin.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Bastiodon", "bastiodon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Bayleef", "bayleef.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Beartic", "beartic.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), NULL),
	("Beautifly", "beautifly.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Beedrill", "beedrill.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Beheeyem", "beheeyem.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Beldum", "beldum.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Bellossom", "bellossom.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Bellsprout", "bellsprout.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Bergmite", "bergmite.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), NULL),
	("Bewear", "bewear.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING")),
	("Bibarel", "bibarel.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="WATER")),
	("Bidoof", "bidoof.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Binacle", "binacle.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Bisharp", "bisharp.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DARK"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Blastoise", "blastoise.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Blaziken", "blaziken.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING")),
	("Blissey", "blissey.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Blitzle", "blitzle.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Boldore", "boldore.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), NULL),
	("Bonsly", "bonsly.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), NULL),
	("Bouffalant", "bouffalant.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Bounsweet", "bounsweet.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Braixen", "braixen.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Braviary", "braviary.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Breloom", "breloom.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING")),
	("Brionne", "brionne.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Bronzong", "bronzong.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Bronzor", "bronzor.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Bruxish", "bruxish.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Budew", "budew.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Buizel", "buizel.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Bulbasaur", "bulbasaur.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Buneary", "buneary.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Bunnelby", "bunnelby.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Burmy", "burmy.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), NULL),
	("Butterfree", "butterfree.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Buzzwole", "buzzwole.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Cacnea", "cacnea.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Cacturne", "cacturne.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Camerupt", "camerupt.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND")),
	("Carbink", "carbink.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Carnivine", "carnivine.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Carracosta", "carracosta.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Carvanha", "carvanha.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Cascoon", "cascoon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), NULL),
	("Castform", "castform.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Caterpie", "caterpie.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), NULL),
	("Celebi", "celebi.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Celesteela", "celesteela.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Chandelure", "chandelure.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Chansey", "chansey.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Charizard", "charizard.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Charjabug", "charjabug.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Charmander", "charmander.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Charmeleon", "charmeleon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Chatot", "chatot.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Cherrim", "cherrim.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Cherubi", "cherubi.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Chesnaught", "chesnaught.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING")),
	("Chespin", "chespin.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Chikorita", "chikorita.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Chimchar", "chimchar.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Chimecho", "chimecho.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Chinchou", "chinchou.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC")),
	("Chingling", "chingling.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Cinccino", "cinccino.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Clamperl", "clamperl.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Clauncher", "clauncher.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Clawitzer", "clawitzer.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Claydol", "claydol.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Clefable", "clefable.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY"), NULL),
	("Clefairy", "clefairy.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY"), NULL),
	("Cleffa", "cleffa.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY"), NULL),
	("Cloyster", "cloyster.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="ICE")),
	("Cobalion", "cobalion.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Cofagrigus", "cofagrigus.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST"), NULL),
	("Combee", "combee.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Combusken", "combusken.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING")),
	("Comfey", "comfey.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY"), NULL),
	("Conkeldurr", "conkeldurr.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Corphish", "corphish.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Corsola", "corsola.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Cosmoem", "cosmoem.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Cosmog", "cosmog.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Cottonee", "cottonee.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Crabominable", "crabominable.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING")),
	("Crabrawler", "crabrawler.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Cradily", "cradily.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Cranidos", "cranidos.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), NULL),
	("Crawdaunt", "crawdaunt.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Cresselia", "cresselia.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Croagunk", "croagunk.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Crobat", "crobat.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Croconaw", "croconaw.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Crustle", "crustle.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Cryogonal", "cryogonal.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), NULL),
	("Cubchoo", "cubchoo.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), NULL),
	("Cubone", "cubone.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), NULL),
	("Cutiefly", "cutiefly.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Cyndaquil", "cyndaquil.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Darkrai", "darkrai.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DARK"), NULL),
	("Darmanitan", "darmanitan.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Dartrix", "dartrix.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Darumaka", "darumaka.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Decidueye", "decidueye.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Dedenne", "dedenne.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Deerling", "deerling.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS")),
	("Deino", "deino.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Delcatty", "delcatty.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Delibird", "delibird.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Delphox", "delphox.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Deoxys", "deoxys.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Dewgong", "dewgong.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="ICE")),
	("Dewott", "dewott.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Dewpider", "dewpider.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Dhelmise", "dhelmise.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Dialga", "dialga.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Diancie", "diancie.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Diggersby", "diggersby.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND")),
	("Digletta", "digletta.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Diglett", "diglett.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), NULL),
	("Ditto", "ditto.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Dodrio", "dodrio.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Doduo", "doduo.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Donphan", "donphan.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), NULL),
	("Doublade", "doublade.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Dragalge", "dragalge.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Dragonair", "dragonair.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON"), NULL),
	("Dragonite", "dragonite.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Drampa", "drampa.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Drapion", "drapion.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Dratini", "dratini.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON"), NULL),
	("Drifblim", "drifblim.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Drifloon", "drifloon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Drilbur", "drilbur.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), NULL),
	("Drowzee", "drowzee.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Druddigon", "druddigon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON"), NULL),
	("Ducklett", "ducklett.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Dugtrioa", "dugtrioa.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Dugtrio", "dugtrio.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), NULL),
	("Dunsparce", "dunsparce.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Duosion", "duosion.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Durant", "durant.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Dusclops", "dusclops.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST"), NULL),
	("Dusknoir", "dusknoir.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST"), NULL),
	("Duskull", "duskull.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST"), NULL),
	("Dustox", "dustox.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Dwebble", "dwebble.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Eelektrik", "eelektrik.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Eelektross", "eelektross.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Eevee", "eevee.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Ekans", "ekans.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), NULL),
	("Electabuzz", "electabuzz.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Electivire", "electivire.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Electrike", "electrike.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Electrode", "electrode.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Elekid", "elekid.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Elgyem", "elgyem.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Emboar", "emboar.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING")),
	("Emolga", "emolga.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Empoleon", "empoleon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Entei", "entei.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Escavalier", "escavalier.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Espeon", "espeon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Espurr", "espurr.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Excadrill", "excadrill.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Exeggcute", "exeggcute.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Exeggutora", "exeggutora.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Exeggutor", "exeggutor.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Exploud", "exploud.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Farfetchd", "farfetchd.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Fearow", "fearow.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Feebas", "feebas.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Fennekin", "fennekin.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Feraligatr", "feraligatr.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Ferroseed", "ferroseed.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Ferrothorn", "ferrothorn.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Finneon", "finneon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Flaaffy", "flaaffy.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Flabebe", "flabebe.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY"), NULL),
	("Flareon", "flareon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Fletchinder", "fletchinder.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Fletchling", "fletchling.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Floatzel", "floatzel.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Floette", "floette.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY"), NULL),
	("Florges", "florges.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY"), NULL),
	("Flygon", "flygon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Fomantis", "fomantis.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Foongus", "foongus.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Forretress", "forretress.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Fraxure", "fraxure.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON"), NULL),
	("Frillish", "frillish.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Froakie", "froakie.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Frogadier", "frogadier.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Froslass", "froslass.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Furfrou", "furfrou.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Furret", "furret.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Gabite", "gabite.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Gallade", "gallade.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Galvantula", "galvantula.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Garbodor", "garbodor.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), NULL),
	("Garchomp", "garchomp.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Gardevoir", "gardevoir.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Gastly", "gastly.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Gastrodon", "gastrodon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND")),
	("Genesect", "genesect.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Gengar", "gengar.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Geodudea", "geodudea.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Geodude", "geodude.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Gible", "gible.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Gigalith", "gigalith.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), NULL),
	("Girafarig", "girafarig.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Giratina", "giratina.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Glaceon", "glaceon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), NULL),
	("Glalie", "glalie.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), NULL),
	("Glameow", "glameow.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Gligar", "gligar.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Gliscor", "gliscor.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Gloom", "gloom.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Gogoat", "gogoat.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Golbat", "golbat.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Goldeen", "goldeen.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Golduck", "golduck.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Golema", "golema.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Golem", "golem.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Golett", "golett.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Golisopod", "golisopod.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Golurk", "golurk.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Goodra", "goodra.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON"), NULL),
	("Goomy", "goomy.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON"), NULL),
	("Gorebyss", "gorebyss.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Gothita", "gothita.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Gothitelle", "gothitelle.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Gothorita", "gothorita.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Gourgeist", "gourgeist.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Granbull", "granbull.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY"), NULL),
	("Gravelera", "gravelera.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Graveler", "graveler.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Greninja", "greninja.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Grimera", "grimera.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Grimer", "grimer.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), NULL),
	("Grotle", "grotle.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Groudon", "groudon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), NULL),
	("Grovyle", "grovyle.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Growlithe", "growlithe.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Grubbin", "grubbin.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), NULL),
	("Grumpig", "grumpig.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Gulpin", "gulpin.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), NULL),
	("Gumshoos", "gumshoos.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Gurdurr", "gurdurr.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Guzzlord", "guzzlord.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Gyarados", "gyarados.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Hakamo-o", "hakamoo.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Happiny", "happiny.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Hariyama", "hariyama.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Haunter", "haunter.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Hawlucha", "hawlucha.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Haxorus", "haxorus.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON"), NULL),
	("Heatmor", "heatmor.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Heatran", "heatran.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Heliolisk", "heliolisk.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC")),
	("Helioptile", "helioptile.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC")),
	("Heracross", "heracross.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Herdier", "herdier.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Hippopotas", "hippopotas.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), NULL),
	("Hippowdon", "hippowdon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), NULL),
	("Hitmonchan", "hitmonchan.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Hitmonlee", "hitmonlee.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Hitmontop", "hitmontop.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Ho-oh", "hooh.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Honchkrow", "honchkrow.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Honedge", "honedge.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Hoopa", "hoopa.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Hoothoot", "hoothoot.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Hoppip", "hoppip.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Horsea", "horsea.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Houndoom", "houndoom.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Houndour", "houndour.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Huntail", "huntail.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Hydreigon", "hydreigon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Hypno", "hypno.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Igglybuff", "igglybuff.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Illumise", "illumise.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), NULL),
	("Incineroar", "incineroar.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Infernape", "infernape.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING")),
	("Inkay", "inkay.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Ivysaur", "ivysaur.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Jangmo-o", "jangmoo.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON"), NULL),
	("Jellicent", "jellicent.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Jigglypuff", "jigglypuff.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Jirachi", "jirachi.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Jolteon", "jolteon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Joltik", "joltik.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Jumpluff", "jumpluff.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Jynx", "jynx.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Kabuto", "kabuto.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Kabutops", "kabutops.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Kadabra", "kadabra.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Kakuna", "kakuna.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Kangaskhan", "kangaskhan.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Karrablast", "karrablast.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), NULL),
	("Kartana", "kartana.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Kecleon", "kecleon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Keldeo", "keldeo.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING")),
	("Kingdra", "kingdra.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Kingler", "kingler.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Kirlia", "kirlia.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Klang", "klang.png", (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL"), NULL),
	("Klefki", "klefki.png", (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Klink", "klink.png", (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL"), NULL),
	("Klinklang", "klinklang.png", (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL"), NULL),
	("Koffing", "koffing.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), NULL),
	("Komala", "komala.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Kommo-o", "kommo-o.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Krabby", "krabby.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Kricketot", "kricketot.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), NULL),
	("Kricketune", "kricketune.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), NULL),
	("Krokorok", "krokorok.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Krookodile", "krookodile.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Kyogre", "kyogre.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Kyurem", "kyurem.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Lairon", "lairon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Lampent", "lampent.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Landorus", "landorus.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Lanturn", "lanturn.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC")),
	("Lapras", "lapras.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="ICE")),
	("Larvesta", "larvesta.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Larvitar", "larvitar.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Latias", "latias.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Latios", "latios.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Leafeon", "leafeon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Leavanny", "leavanny.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Ledian", "ledian.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Ledyba", "ledyba.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Lickilicky", "lickilicky.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Lickitung", "lickitung.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Liepard", "liepard.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DARK"), NULL);

INSERT INTO `Pokemon` (`Name`,`ImagePath`, `TypeFirst`, `TypeSecond`) VALUES
	("Lileep", "lileep.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Lilligant", "lilligant.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Lillipup", "lillipup.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Linoone", "linoone.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Litleo", "litleo.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE")),
	("Litten", "litten.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Litwick", "litwick.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Lombre", "lombre.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS")),
	("Lopunny", "lopunny.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Lotad", "lotad.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS")),
	("Loudred", "loudred.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Lucario", "lucario.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Ludicolo", "ludicolo.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS")),
	("Lugia", "lugia.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Lumineon", "lumineon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Lunala", "lunala.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Lunatone", "lunatone.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Lurantis", "lurantis.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Luvdisc", "luvdisc.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Luxio", "luxio.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Luxray", "luxray.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Lycanrock", "lycanrock.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), NULL),
	("Machamp", "machamp.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Machoke", "machoke.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Machop", "machop.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Magby", "magby.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Magcargo", "magcargo.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Magearna", "magearna.png", (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Magikarp", "magikarp.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Magmar", "magmar.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Magmortar", "magmortar.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Magnemite", "magnemite.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Magneton", "magneton.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Magnezone", "magnezone.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Makuhita", "makuhita.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Malamar", "malamar.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Mamoswine", "mamoswine.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND")),
	("Manaphy", "manaphy.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Mandibuzz", "mandibuzz.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Manectric", "manectric.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Mankey", "mankey.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Mantine", "mantine.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Mantyke", "mantyke.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Maractus", "maractus.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Mareanie", "mareanie.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Mareep", "mareep.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Marill", "marill.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Marowaka", "marowaka.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Marowak", "marowak.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), NULL),
	("Marshadow", "marshadow.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Marshtomp", "marshtomp.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND")),
	("Masquerain", "masquerain.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Mawile", "mawile.png", (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Medicham", "medicham.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Meditite", "meditite.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Meganium", "meganium.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Meloetta", "meloetta.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING")),
	("Meowstic", "meowstic.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Meowtha", "meowtha.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DARK"), NULL),
	("Meowth", "meowth.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Mesprit", "mesprit.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Metagross", "metagross.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Metang", "metang.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Metapod", "metapod.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), NULL),
	("Mew", "mew.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Mewtwo", "mewtwo.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Mienfoo", "mienfoo.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Mienshao", "mienshao.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Mightyena", "mightyena.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DARK"), NULL),
	("Milotic", "milotic.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Miltank", "miltank.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Mime-jr", "mimejr.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Mimikyu", "mimikyu.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Minccino", "minccino.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Minior", "minior.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Minun", "minun.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Misdreavus", "misdreavus.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST"), NULL),
	("Mismagius", "mismagius.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST"), NULL),
	("Moltres", "moltres.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Monferno", "monferno.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING")),
	("Morelull", "morelull.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Mothim", "mothim.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Mr-mime", "mrmime.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Mudbray", "mudbray.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), NULL),
	("Mudkip", "mudkip.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Mudsdale", "mudsdale.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), NULL),
	("Muka", "muka.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Muk", "muk.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), NULL),
	("Munchlax", "munchlax.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Munna", "munna.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Murkrow", "murkrow.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Musharna", "musharna.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Natu", "natu.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Necrozma", "necrozma.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Nidoking", "nidoking.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND")),
	("Nidoqueen", "nidoqueen.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND")),
	("Nidoran-f", "nidoranf.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), NULL),
	("Nidoran-m", "nidoranm.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), NULL),
	("Nidorina", "nidorina.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), NULL),
	("Nidorino", "nidorino.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), NULL),
	("Nihilego", "nihilego.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Nincada", "nincada.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Ninetalesa", "ninetalesa.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Ninetales", "ninetales.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Ninjask", "ninjask.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Noctowl", "noctowl.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Noibat", "noibat.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Noivern", "noivern.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Nosepass", "nosepass.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), NULL),
	("Numel", "numel.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND")),
	("Nuzleaf", "nuzleaf.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Octillery", "octillery.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Oddish", "oddish.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Omanyte", "omanyte.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Omastar", "omastar.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Onix", "onix.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Oranguru", "oranguru.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Oricorido", "oricorido.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Oshawott", "oshawott.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Pachirisu", "pachirisu.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Palkia", "palkia.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Palossand", "palossand.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Palpitoad", "palpitoad.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND")),
	("Pancham", "pancham.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Pangoro", "pangoro.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Panpour", "panpour.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Pansage", "pansage.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Pansear", "pansear.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Paras", "paras.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Parasect", "parasect.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Passimian", "passimian.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Patrat", "patrat.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Pawniard", "pawniard.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DARK"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Pelipper", "pelipper.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Persiana", "persiana.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DARK"), NULL),
	("Persian", "persian.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Petilil", "petilil.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Phanpy", "phanpy.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), NULL),
	("Phantump", "phantump.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Pheromosa", "pheromosa.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Phione", "phione.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Pichu", "pichu.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Pidgeot", "pidgeot.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Pidgeotto", "pidgeotto.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Pidgey", "pidgey.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Pidove", "pidove.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Pignite", "pignite.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING")),
	("Pikachu", "pikachu.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Pikipek", "pikipek.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Piloswine", "piloswine.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND")),
	("Pineco", "pineco.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), NULL),
	("Pinsir", "pinsir.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), NULL),
	("Piplup", "piplup.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Plusle", "plusle.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Politoed", "politoed.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Poliwag", "poliwag.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Poliwhirl", "poliwhirl.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Poliwrath", "poliwrath.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING")),
	("Ponyta", "ponyta.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Poochyena", "poochyena.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DARK"), NULL),
	("Popplio", "popplio.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Porygon-z", "porygonz.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Porygon2", "porygon2.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Porygon", "porygon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Primarina", "primarina.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Primeape", "primeape.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Prinplup", "prinplup.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Probopass", "probopass.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Psyduck", "psyduck.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Pumpkaboo", "pumpkaboo.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Pupitar", "pupitar.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Purrloin", "purrloin.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DARK"), NULL),
	("Purugly", "purugly.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Pyroar", "pyroar.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE")),
	("Pyukumuku", "pyukumuku.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Quagsire", "quagsire.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND")),
	("Quilava", "quilava.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Quilladin", "quilladin.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Qwilfish", "qwilfish.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Raichua", "raichua.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Raichu", "raichu.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Raikou", "raikou.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Ralts", "ralts.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Rampardos", "rampardos.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), NULL),
	("Rapidash", "rapidash.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Raticatea", "raticatea.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Raticate", "raticate.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Rattataa", "rattataa.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Rattata", "rattata.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Rayquaza", "rayquaza.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Regice", "regice.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), NULL),
	("Regigigas", "regigigas.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Regirock", "regirock.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), NULL),
	("Registeel", "registeel.png", (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL"), NULL),
	("Relicanth", "relicanth.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Remoraid", "remoraid.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Reshiram", "reshiram.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Reuniclus", "reuniclus.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Rhydon", "rhydon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Rhyhorn", "rhyhorn.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Rhyperior", "rhyperior.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Ribombee", "ribombee.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Riolu", "riolu.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Rockruff", "rockruff.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), NULL),
	("Roggenrola", "roggenrola.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), NULL),
	("Roselia", "roselia.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Roserade", "roserade.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Rotom", "rotom.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Rowlet", "rowlet.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Rufflet", "rufflet.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Sableye", "sableye.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Salamence", "salamence.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Salandit", "salandit.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Salazzle", "salazzle.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Samurott", "samurott.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Sandile", "sandile.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Sandshrewa", "sandshrewa.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Sandshrew", "sandshrew.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), NULL),
	("Sandslasha", "sandslasha.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Sandslash", "sandslash.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), NULL),
	("Sandygast", "sandygast.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Sawk", "sawk.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Sawsbuck", "sawsbuck.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS")),
	("Scatterbug", "scatterbug.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), NULL),
	("Sceptile", "sceptile.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Scizor", "scizor.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Scolipede", "scolipede.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Scrafty", "scrafty.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Scraggy", "scraggy.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Scyther", "scyther.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Seadra", "seadra.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Seaking", "seaking.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Sealeo", "sealeo.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="ICE")),
	("Seedot", "seedot.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Seel", "seel.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Seismitoad", "seismitoad.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND")),
	("Sentret", "sentret.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Serperior", "serperior.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Servine", "servine.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Seviper", "seviper.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), NULL),
	("Sewaddle", "sewaddle.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Sharpedo", "sharpedo.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Shaymin", "shaymin.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Shedinja", "shedinja.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Shelgon", "shelgon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON"), NULL),
	("Shellder", "shellder.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Shellos", "shellos.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Shelmet", "shelmet.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), NULL),
	("Shieldon", "shieldon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Shiftry", "shiftry.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Shiinotic", "shiinotic.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Shinx", "shinx.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Shroomish", "shroomish.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Shuckle", "shuckle.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Shuppet", "shuppet.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST"), NULL),
	("Sigilyph", "sigilyph.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Silcoon", "silcoon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), NULL),
	("Silvally", "silvally.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Simipour", "simipour.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Simisage", "simisage.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Simisear", "simisear.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Skarmory", "skarmory.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Skiddo", "skiddo.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Skiploom", "skiploom.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Skitty", "skitty.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Skorupi", "skorupi.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Skrelp", "skrelp.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Skuntank", "skuntank.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Slaking", "slaking.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Slakoth", "slakoth.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Sliggoo", "sliggoo.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON"), NULL),
	("Slowbro", "slowbro.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Slowking", "slowking.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Slowpoke", "slowpoke.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Slugma", "slugma.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Slurpuff", "slurpuff.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY"), NULL),
	("Smeargle", "smeargle.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Smoochum", "smoochum.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Sneasel", "sneasel.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Snivy", "snivy.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Snorlax", "snorlax.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Snorunt", "snorunt.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), NULL),
	("Snover", "snover.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="ICE")),
	("Snubbull", "snubbull.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY"), NULL),
	("Solgaleo", "solgaleo.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Solosis", "solosis.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Solrock", "solrock.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Spearow", "spearow.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Spewpa", "spewpa.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), NULL),
	("Spheal", "spheal.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="ICE")),
	("Spinarak", "spinarak.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Spinda", "spinda.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Spiritomb", "spiritomb.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Spoink", "spoink.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Spritzee", "spritzee.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY"), NULL),
	("Squirtle", "squirtle.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Stantler", "stantler.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Staraptor", "staraptor.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Staravia", "staravia.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Starly", "starly.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Starmie", "starmie.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Staryu", "staryu.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Steelix", "steelix.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Steenee", "steenee.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Stoutland", "stoutland.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Stufful", "stufful.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING")),
	("Stunfisk", "stunfisk.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND")),
	("Stunky", "stunky.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Sudowoodo", "sudowoodo.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), NULL),
	("Suicune", "suicune.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Sunflora", "sunflora.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Sunkern", "sunkern.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Surskit", "surskit.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Swablu", "swablu.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Swadloon", "swadloon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Swalot", "swalot.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), NULL),
	("Swampert", "swampert.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND")),
	("Swanna", "swanna.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Swellow", "swellow.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Swinub", "swinub.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND")),
	("Swirlix", "swirlix.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY"), NULL),
	("Swoobat", "swoobat.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Sylveon", "sylveon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY"), NULL),
	("Taillow", "taillow.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Talonflame", "talonflame.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Tangela", "tangela.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Tangrowth", "tangrowth.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Tapu-bulu", "tapubulu.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Tapu-fini", "tapufini.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Tapu-koko", "tapukoko.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Tapu-lele", "tapulele.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Tauros", "tauros.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Teddiursa", "teddiursa.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Tentacool", "tentacool.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Tentacruel", "tentacruel.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Tepig", "tepig.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Terrakion", "terrakion.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Throh", "throh.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Thundurus", "thundurus.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Timburr", "timburr.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Tirtouga", "tirtouga.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK")),
	("Togedemaru", "togedemaru.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="STEEL")),
	("Togekiss", "togekiss.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Togepi", "togepi.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY"), NULL),
	("Togetic", "togetic.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Torchic", "torchic.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Torkoal", "torkoal.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Tornadus", "tornadus.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), NULL),
	("Torracat", "torracat.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Torterra", "torterra.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND")),
	("Totodile", "totodile.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Toucannon", "toucannon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Toxapex", "toxapex.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Toxicroak", "toxicroak.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Tranquill", "tranquill.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Trapinch", "trapinch.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), NULL),
	("Treecko", "treecko.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Trevenant", "trevenant.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST")),
	("Tropius", "tropius.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Trubbish", "trubbish.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), NULL),
	("Trumbeak", "trumbeak.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Tsareena", "tsareena.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Turtonator", "turtonator.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Turtwig", "turtwig.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), NULL),
	("Tympole", "tympole.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Tynamo", "tynamo.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Type-null", "type-null.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Typhlosion", "typhlosion.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Tyranitar", "tyranitar.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Tyrantrum", "tyrantrum.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Tyrogue", "tyrogue.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING"), NULL),
	("Tyrunt", "tyrunt.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ROCK"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Umbreon", "umbreon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DARK"), NULL),
	("Unfezant", "unfezant.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Unown", "unown.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Ursaring", "ursaring.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Uxie", "uxie.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Vanillish", "vanillish.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), NULL),
	("Vanillite", "vanillite.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), NULL),
	("Vanilluxe", "vanilluxe.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), NULL),
	("Vaporeon", "vaporeon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Venipede", "venipede.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Venomoth", "venomoth.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Venonat", "venonat.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Venusaur", "venusaur.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Vespiquen", "vespiquen.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Vibrava", "vibrava.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Victini", "victini.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Victreebel", "victreebel.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Vigoroth", "vigoroth.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Vikavolt", "vikavolt.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Vileplume", "vileplume.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Virizion", "virizion.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="FIGHTING")),
	("Vivillon", "vivillon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Volbeat", "volbeat.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), NULL),
	("Volcanion", "volcanion.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="WATER")),
	("Volcarona", "volcarona.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Voltorb", "voltorb.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Vullaby", "vullaby.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Vulpixa", "vulpixa.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), NULL),
	("Vulpix", "vulpix.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FIRE"), NULL),
	("Wailmer", "wailmer.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Wailord", "wailord.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Walrein", "walrein.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="ICE")),
	("Wartortle", "wartortle.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Watchog", "watchog.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Weavile", "weavile.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ICE"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Weedle", "weedle.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Weepinbell", "weepinbell.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="POISON")),
	("Weezing", "weezing.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), NULL),
	("Whimsicott", "whimsicott.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Whirlipede", "whirlipede.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Whiscash", "whiscash.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND")),
	("Whismur", "whismur.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Wigglytuff", "wigglytuff.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY")),
	("Wimpod", "wimpod.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Wingull", "wingull.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Wishiwashi", "wishiwashi.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), NULL),
	("Wobbuffet", "wobbuffet.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Woobat", "woobat.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Wooper", "wooper.png", (SELECT `Id` FROM PokemonType WHERE `Name`="WATER"), (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND")),
	("Wormadam", "wormadam.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GRASS"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Wurmple", "wurmple.png", (SELECT `Id` FROM PokemonType WHERE `Name`="BUG"), NULL),
	("Wynaut", "wynaut.png", (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC"), NULL),
	("Xatu", "xatu.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="PSYCHIC")),
	("Xerneas", "xerneas.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FAIRY"), NULL),
	("Xurkitree", "xurkitree.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Yamask", "yamask.png", (SELECT `Id` FROM PokemonType WHERE `Name`="GHOST"), NULL),
	("Yanma", "yanma.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Yanmega", "yanmega.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="BUG")),
	("Yungoos", "yungoos.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Yveltal", "yveltal.png", (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Zangoose", "zangoose.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Zapdos", "zapdos.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Zebstrika", "zebstrika.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), NULL),
	("Zekrom", "zekrom.png", (SELECT `Id` FROM PokemonType WHERE `Name`="ELECTRIC"), (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON")),
	("Zigzagoon", "zigzagoon.png", (SELECT `Id` FROM PokemonType WHERE `Name`="NORMAL"), NULL),
	("Zoroark", "zoroark.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DARK"), NULL),
	("Zorua", "zorua.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DARK"), NULL),
	("Zubat", "zubat.png", (SELECT `Id` FROM PokemonType WHERE `Name`="POISON"), (SELECT `Id` FROM PokemonType WHERE `Name`="FLYING")),
	("Zweilous", "zweilous.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON"), (SELECT `Id` FROM PokemonType WHERE `Name`="DARK")),
	("Zygarde", "zygarde.png", (SELECT `Id` FROM PokemonType WHERE `Name`="DRAGON"), (SELECT `Id` FROM PokemonType WHERE `Name`="GROUND"));
COMMIT;
